### ISSUE TITLE
Simple instructions on README on how to test this while under construction

### ISSUE THREAD

**Issue by lipis** [prettier/plugin-python#11]
I think it would be a good idea to have some simple instructions on how can someone test the Python integration on their own projects in the current state. Obviously it's not final on how it will work in the end, but since it's under construction anyway it will be much easier for new comers to test it with instructions.

**Comment by j-f1** [comment]
If you view the README’s raw source, there’s instructions in an HTML comment.

**Comment by azz** [comment]
I don't think it's in a testable state just yet, it requires downloading a specific commit of Prettier.

**Comment by taion** [comment]
They also don't quite work yet. Need https://github.com/prettier/prettier/pull/3584 and https://github.com/prettier/prettier-python/pull/13.

**Comment by FuegoFro** [comment]
The README now describes how to build and run the formatter, which I think should be sufficient for running it on one's own project. It also now links to the main repo's CONTRIBUTING guide, which describes the`yarn test` command needed to run the tests.

Does that seem sufficient to close out this issue?

**Comment by j-f1** [comment]
I think so 👍
