### ISSUE TITLE
Different default line width for Python?

### ISSUE THREAD

**Issue by taion** [prettier/plugin-python#14]
PEP 8 specifies a max line width of 79: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

People can and do override this, but it would be nice if the no-config default for Python were 79 instead of 80, somehow.

**Comment by taion** [comment]
Oops, forgot to add an issue body. Added above.

**Comment by taion** [comment]
And, yes, I agree that 79 specifically is sort of weird, but it's what PEP 8 says.

**Comment by azz** [comment]
We should export `defaultOptions` from the plugin as 

```js
{
  printWidth: 79,
  tabWidth: 4
}
```

And then apply it in `normalize()` in Prettier.

**Comment by patrick91** [comment]
@azz is this something we can already do or we need some changes in prettier itself?

**Comment by azz** [comment]
Still needs some changes to Prettier, see https://github.com/prettier/prettier/issues/3615

**Comment by mgrip** [comment]
Not sure that PR allowed default option values to be override (it did add php-specific options though). We ran into the same plugin w/ the php plugin and opened this issue https://github.com/prettier/prettier/issues/3972
