### ISSUE TITLE
Add python tests suite

### ISSUE THREAD

**Issue by patrick91** [prettier/plugin-python#3]
I had started a small repo with a python test suite here: https://github.com/patrick91/prettier-python-tests

Now that we have a separate repo we could add these tests here, instead of having a separate repo.

**Comment by vjeux** [comment]
The best way to get a good test suite is to always add a test for each pull request. Would be nice to find an existing one to get bootstrapped, but that's not necessarily needed. Once enough of the language is pretty printed, running prettier on existing codebases is the easiest way to find out things to improve :)

**Comment by FuegoFro** [comment]
Just curious, is this relevant? Seems like we have a fairly decent test suite, and it's growing over time with each commit.

**Comment by patrick91** [comment]
We can close this! :)
