### ISSUE TITLE
Support for mypy types? 

### ISSUE THREAD

**Issue by mohsen1** [prettier/plugin-python#35]
I noticed this plugin is stripping type hints. Where is supporting type hints in your roadmap?

**Comment by patrick91** [comment]
@mohsen1 yes I think we will! Would you mind to submit a PR with failing tests? so some can pick that and work on it :)

**Comment by patrick91** [comment]
@mohsen1 #40 added support for type annotations, can you have a try? :)

**Comment by FuegoFro** [comment]
I'm gonna go ahead and close this out due to the support that's been landed :) If you find an issue with mypy types feel free to re-open this or file a new issue!

**Comment by mohsen1** [comment]
Thanks!
