### ISSUE TITLE
What the fudge does this do?

### ISSUE THREAD

**Issue by SomaBots** [prettier/plugin-python#45]
There is no description.

**Comment by j-f1** [comment]
The Prettier docs explain this pretty well: [What is Prettier?](https://prettier.io/docs/en/index.html) & [Why Prettier?](https://prettier.io/docs/en/why-prettier.html).

**Comment by azz** [comment]
Yep. This is a plugin to pretty-print Python code. It's still unreleased so the docs are lacking.
