### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by FezVrasta** [prettier/plugin-python#98]
Hi, if I try to prettier this code I get the error in the title.

https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/HueEmulator3.py

**Comment by ryanashcraft** [comment]
@FezVrasta This is likely because you don't have `python3` in your PATH or you're not running prettier with `--python-version=3`.

We should check for this and provide a better error message when this happens.

**Comment by FezVrasta** [comment]
I do have python3 in PATH, but I didn't use the flag you mentioned, thanks
